const GAME_CONFIG = {
  initialBalance: 100,
  fixedBet: 10,
  columnCount: 6,
  rowCount: 5,
  symbols: [
    {
      id: "cherry",
      icon: "🍒",
      weight: 18,
      minCount: 7,
      baseMultiplier: 0.03,
      extraMultiplier: 0.009,
    },
    {
      id: "lemon",
      icon: "🍋",
      weight: 17,
      minCount: 7,
      baseMultiplier: 0.042,
      extraMultiplier: 0.012,
    },
    {
      id: "grape",
      icon: "🍇",
      weight: 16,
      minCount: 7,
      baseMultiplier: 0.054,
      extraMultiplier: 0.015,
    },
    {
      id: "bell",
      icon: "🔔",
      weight: 14,
      minCount: 7,
      baseMultiplier: 0.084,
      extraMultiplier: 0.021,
    },
    {
      id: "clover",
      icon: "🍀",
      weight: 12,
      minCount: 7,
      baseMultiplier: 0.132,
      extraMultiplier: 0.03,
    },
    {
      id: "diamond",
      icon: "💎",
      weight: 10,
      minCount: 7,
      baseMultiplier: 0.228,
      extraMultiplier: 0.048,
    },
    {
      id: "seven",
      icon: "7️⃣",
      weight: 8,
      minCount: 7,
      baseMultiplier: 0.42,
      extraMultiplier: 0.084,
    },
  ],
  spinDurationMs: 900,
  animationTickMs: 120,
  winFlashMs: 650,
  clearDelayMs: 260,
  tumbleDropMs: 420,
  cascadePauseMs: 240,
};

window.GAME_CONFIG = GAME_CONFIG;
